import Header from "./components/Header";
import { DM_Sans } from "next/font/google"
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const dm_sans = DM_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={dm_sans.className}>
      <body suppressHydrationWarning={true} >
        <Header />
        {children}
      </body>
    </html>
  )
}
